### ISSUE TITLE
Twitter Login API broken

### ISSUE THREAD

**Issue by reznyt** [mvdicarlo/postybirb-plus#102]
Cannot add a twitter account to PostyBirb. Clicking "Login" results in a page which states "A problem occurred when attempting to contact the authentication server." And seems to ask for a manual Authentication PIN.

![image](https://user-images.githubusercontent.com/7978804/170877290-d8095f0b-8f28-432f-869a-3a0fde7437e5.png)

On inspection of the related code, the login flow appears to depend on a custom auth server, which returns an error when authorizing.

![image](https://user-images.githubusercontent.com/7978804/170877387-574347dc-9b8d-4887-a033-0e4634ec2e30.png)

**Comment by mvdicarlo** [comment]
Known issue. Not our fault.
Awaiting Twitter to respond to ticket on why they blocked the api to the app.

**Comment by reznyt** [comment]
Just applying occam's razor ... you've done this, right?

```
Code 261 - Application cannot perform write actions.
The app that you are using with the API does not have the proper permission level
set for its access token and access token secret. Please navigate to the 'Keys and tokens' tab on the Twitter apps
dashboard and check the permission levels assigned to your access token and access token secret.
If it is set to anything other than 'Read, write and Direct Messages,' then you are going to have to adjust 
the settings under the 'Permission' tab and regenerate your access token and access token secret to apply the new settings.
```

**Comment by reznyt** [comment]
Appears to be working now, confirmed fixed.

**Comment by Mandraw** [comment]
Still gets me this error, should I install directly from git ? I'm currently using the .exe installation
