### ISSUE TITLE
SESSION_PASSWORD_NEEDED when adding Telegram account

### ISSUE THREAD

**Issue by VojtechL** [mvdicarlo/postybirb-plus#151]
When trying to connect PostyBirb to an account that has 2FA enabled Telegram responds with SESSION_PASSWORD_NEEDED
![image](https://user-images.githubusercontent.com/91225380/225147543-60cff742-d133-4df4-a1dc-f5ddd0973dfe.png)

Workaround is to disable 2FA, then PostyBirb is able to successfully connect.

I'm not sure if you can fix it on your side but could you add a helpful error message so the user knows what to do?

**Comment by leaftail1880** [comment]
Possible fix
https://mtproto-core.js.org/docs/user-authorization#code

**Comment by VojtechL** [comment]
Thanks for fixing it, Postybirb now works with Telegram with 2FA enabled.
