### ISSUE TITLE
Request: Cohost support

### ISSUE THREAD

**Issue by aneillans** [mvdicarlo/postybirb-plus#156]
Just putting this here as a request note more than anything, as seen it around a lot.

Found the library that uses the current Cohost private api and am reviewing it with the plan to put a PR together when I get time. depending on demand, although am conscious this one could be a potential regular breaking one due to it not being fully stable.

**Comment by mvdicarlo** [comment]
To be fair, that somewhat fits in-line with postybirb which uses a lot of private undocumented apis for most websites.

**Comment by aneillans** [comment]
I thought it might 😂

**Comment by TrebleSketch** [comment]
Heyo, I was curious what might be the progress on this feature atm?

Saw someone on cohost's support forum asking about if cohost would add postybird support 10 months ago and also found this issue while being curious for if there's been any progress ^w^

**Comment by aneillans** [comment]
No progress; they were going to release an API so I was waiting for that (and working on other features), but then they pulled it at the last minute.  Rumour has it "its back on schedule" so ... who knows.  If they ever release an API, I'll look at doing an integration; I just don't want to spend time doing a "hacky" integration that we then have to reverse out for a proper API shortly after :/

**Comment by TrebleSketch** [comment]
eeyup, that is fair and hopefully something will be released from them in the near future ^^

can understand not wanting to basically implement it twice :P

**Comment by RonaldZielaznicki** [comment]
Dropping in to upvote my interest in the feature and to also offer @aneillans assistance in cobbling it together if y'all are willing to collab on it.

**Comment by SomewhatDamaged** [comment]
Cohost have announced they are shutting down.
https://cohost.org/staff/post/7611443-cohost-to-shut-down
