### ISSUE TITLE
Unable to link Fur Affinity account

### ISSUE THREAD

**Issue by buxy-xyz** [mvdicarlo/postybirb-plus#172]
as the title states im running into issues with linking my FA account to postybirb+.
it constantly displays green light but prompts "not logged in" inside the account tab.

![0PpmOIU](https://github.com/mvdicarlo/postybirb-plus/assets/47367285/0c71bfb1-0ee4-42d6-892a-4d41820b3c05)

mirror: https://i.imgur.com/0PpmOIU.png

i tried hitting the clip button to reset my cookies, nothing happens after logging into the account again inside the small browser window. the same issue persists.

sidenote: i've uploaded over 700 submissions, so it cannot be an issue anything regarding account limitations.

**Comment by leaftail1880** [comment]
Still actual @buxy-xyz ?

**Comment by buxy-xyz** [comment]
> Still actual @buxy-xyz?
> 
> This looks like ui issue

i don't think it's an ui issue, any attempt to try and upload anyway results into an error that i should link my FA account first.
this however is fixed in the 4.X version of postybirb, im not really sure if it's worth keeping this issue open.

**Comment by mvdicarlo** [comment]
As long as it was green it shouldn't impact functionality.
Reopen if impacting usage of app.
