### ISSUE TITLE
Twitter shortcode broken on twitter

### ISSUE THREAD

**Issue by huang-jy** [mvdicarlo/postybirb-plus#173]
I'm using 3.1.20 on Windows 10

When posting an image on Twitter using the `tw` shortcode:

`{tw:something}`

Instead of it showing as "`@something`", it shows as "`@/something`", which breaks the tag entirely.

However, the short code does seem to work on other sites (checked DeviantArt, FurAffinity, Mastodon and Twitter). So I wonder if it's a Musky issue?

**Comment by mvdicarlo** [comment]
Currently this is an intentional change while it is investigated why the app had its api suspended in the first place.

**Comment by huang-jy** [comment]
No problem ,thanks for replying
