### ISSUE TITLE
Roadmap: Make project more contribution-friendly

### ISSUE THREAD

**Issue by leaftail1880** [mvdicarlo/postybirb-plus#207]
When i first tried to contribute, i ran into a lot of problems:

1. Warnings about deprecated and vulnerable dependencies during installation
2. SSL error when running `npm run make` from the project root
3. Confusing installation/build/run scripts
4. Different typescript versions in different folders
5. Different linters, code styles, etc.

I spent a lot of time to figure this out and I don't want anyone else to suffer so much, so I present my roadmap of changes that I will carry out so that this does not happen again (ill open pr for each of them and add link, when pr is closed ill mark task as done):

- [x] #208
   Replace outdated npm-run-all with [npm-run-all2](https://www.npmjs.com/package/npm-run-all2) which also has less dependencies.
- [x] #212  
    Make a single version of typescript, eslint and prettier for all folders, update configurations and plugins.
- [x] #225
  Separate pr because it will be big. Not a problem for pr's made before new codestyle, because it can be fixed by one command
- [x] #228 

### All other changes can only be applied after v4

- [ ] Replace react-scripts with [vite](https://electron-vite.org/)
   react-scripts is outdated, to run it you even have to use `--legacy-ssl-provider` (on nodejs@^16)
   vite is very fast (3-4ms builds instead of 4-5m react-scripts), supports hot relload, it has no outdated dependencies and it is possible to configure support for a specific version of chrome so as not to pack polyfills for already supported functions.
- [ ]  Update README's
- [ ]  Add a contribution guide with a clear description

**Comment by mvdicarlo** [comment]
Apologies for all the trouble you've gone through.
Largely this has been neglected since its only recent that PRs have actually started coming in after so many years.

There is a v4 being worked on that is just a monorepo that tries to solve some of these issues in the long run.

I'll take a closer look when back from vacation.

**Comment by leaftail1880** [comment]
@mvdicarlo 
This pr isn't big, it just modifies some configs/package.json's and some files. I thinl untill v4 is realeased this is the best choice. However, i can't work on it untill firts pr is merged, so ill wait untill you can check that.

**Comment by leaftail1880** [comment]
Closed in favor of v4: github.com/mvdicarlo/postybirb/tree/v4
