### ISSUE TITLE
BUG: Telegram Formatting

### ISSUE THREAD

**Issue by mvdicarlo** [mvdicarlo/postybirb-plus#239]
@leaftail1880 `<p>I've <strong>closed commissions</strong> until 2024 so that...` User reports telegram notifications have broken text.

**Comment by leaftail1880** [comment]
@mvdicarlo 

will check today. By the way, what is the progress of the v4

also, what did you mean about closing comms? Are you an artist?

**Comment by mvdicarlo** [comment]
Apologies, I didn't realize that telegram would format that.
That was meant to be the example string that an artist provided.

**Comment by mvdicarlo** [comment]
As for v4, I was thinking about making a section in the discord to pull all of the contributors in to maybe see if anyone is interested on working on moving it forward faster with me.

Its making progress but I can only get 3-5 hours in on it a week.

**Comment by leaftail1880** [comment]
should be closed now
