### ISSUE TITLE
Mastodon: error message on long content for Pleroma/Akkoma

### ISSUE THREAD

**Issue by bugsysop** [mvdicarlo/postybirb-plus#259]
Content over 500 characters work fine with Pleroma, but we have still an error message:

![screeb-2023-10-12 à 11 10 34](https://github.com/mvdicarlo/postybirb-plus/assets/365281/6e092aaa-aca1-4307-bcf2-5309ab97089c)

**Comment by aneillans** [comment]
As mentioned; Pleroma not officially supported; the Mastodon compatibility API presentation is poor and will cause this sort of false behaviour due to fall backs.

However, PR #262 is to add correct support. So it's coming.
