### ISSUE TITLE
Patreon: No CSRF Token found.

### ISSUE THREAD

**Issue by HaikuOezu** [mvdicarlo/postybirb-plus#274]
Been getting this error for a few days now and I can't figure out what to do
I tried logging out and back in and even deleting and re-adding the account, all posts fail with "Patreon: No CSRF Token found."

**Comment by cat80k** [comment]
I had this same issue too, I was keeping an eye on this ticket/post. Looks like today's update has fixed it, for me at least. I hope yours is working too, stranger.

**Comment by HaikuOezu** [comment]
> I had this same issue too, I was keeping an eye on this ticket/post. Looks like today's update has fixed it, for me at least. I hope yours is working too, stranger.

Oh yeah it did, thanks for reminding me to close this issue!
