### ISSUE TITLE
Newgrounds: All uploads are downscaled to 600x600

### ISSUE THREAD

**Issue by argonvile** [mvdicarlo/postybirb-plus#276]
Around October 16th, Newgrounds started shrinking all Postybirb uploads to 600x600 px. This has been reported by multiple users on the Postybirb discord.

This occurs even if the "Downscale Images" PostyBirb setting is set to false. Uploading images through Newgrounds' website does not shrink the images, this only affects Postybirb.

The full scale images can be reuploaded by editing the Newgrounds submission.

**Comment by mvdicarlo** [comment]
Thanks for the report I might have an idea about why this is happening and will investigate.

**Comment by mvdicarlo** [comment]
Should be fixed in 3.1.34
