### ISSUE TITLE
Unable to post to Fur Affinity and Ko-fi

### ISSUE THREAD

**Issue by OdysseyDutchAngle** [mvdicarlo/postybirb-plus#292]
I wasn't able to find anything at all about this, but apologies if this has already been solved before. I just started using this app (and its great btw!)

I made a submission and entered DeviantArt, Tumblr, Fur Affinity, Newgrounds, and Ko-fi as websites to be posted to. DeviantArt and Tumblr worked fine, but Fur Affinity and Ko-fi entirely failed.

For each of the failed websites I got this error:
`this.formatTags(...).join is not a function`
...this error also appeared for Newgrounds, but while I was writing this issue, I checked my accounts and found out that it had actually posted with the tags and everything else done correctly. 

I don't know what could be causing this. As the Q&A asks, I do have more than 11 posts on Fur Affinity, and I have Ko-Fi gold so that I can post hi-res images. I thought this was a problem with the "Combine with default" feature for tags, but turning that off and adding tags to combine does not solve the issue.

**Comment by mvdicarlo** [comment]
Hmmmm What version are you on?
I wonder if something broke with the latest update.

**Comment by Fisk24** [comment]
i can confirm this bug, and yes this is the latest 3.1.36 build. and it effects more websites then the op mentions. i have a screenshot here showing that it also effects furbooru, e621, furtastic, inkbunny, and pillowfort. seemingly every site that actually cares about tags.
![Screenshot_2023-12-24_08-32-04](https://github.com/mvdicarlo/postybirb-plus/assets/10426444/acd3cca8-b429-4c1e-bbca-af7521568278)

**Comment by Fisk24** [comment]
after checking my pages, i can report that the artwork was not posted to the websites listed in the error message

**Comment by OdysseyDutchAngle** [comment]
> Hmmmm What version are you on? I wonder if something broke with the latest update.

3.1.36, I updated not to long before I got the error. Sorry if I kept you waiting btw.

**Comment by leaftail1880** [comment]
@OdysseyDutchAngle check latest version (3.1.37)

**Comment by Fisk24** [comment]
Will check soon

**Comment by OdysseyDutchAngle** [comment]
> @OdysseyDutchAngle check latest version (3.1.37)

yup! works now. thanks for fixing it!
