### ISSUE TITLE
Patreon "Everyone" Access Tier uploads as Free instead of Paid Members

### ISSUE THREAD

**Issue by catrubs** [mvdicarlo/postybirb-plus#293]
Some new update to Patreon must've changed something because now using the "Everyone" option when uploading will post as for everyone rather than paid members only.

**Comment by mvdicarlo** [comment]
Thanks for the report.

**Comment by mvdicarlo** [comment]
This should be fixed now. Reopen if still experiencing the issue in the latest version.
