### ISSUE TITLE
error when a posting on pixiv

### ISSUE THREAD

**Issue by Archinect** [mvdicarlo/postybirb-plus#306]
"errors": [
   "<div class='error'>Invalid parent folder 0</div>\n",
   "SyntaxError: Unexpected token < in JSON at position 0\nSyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at Pixiv.<anonymous> (file:///C:/Users/ARCHIN~1/AppData/Local/Temp/2H6I6CCfVwB2aamzCL6dxVRmbSB/resources/app.asar/dist/main.js:1:4533740)\n    at step (file:///C:/Users/ARCHIN~1/AppData/Local/Temp/2H6I6CCfVwB2aamzCL6dxVRmbSB/resources/app.asar/dist/main.js:1:554091)\n    at Object.next (file:///C:/Users/ARCHIN~1/AppData/Local/Temp/2H6I6CCfVwB2aamzCL6dxVRmbSB/resources/app.asar/dist/main.js:1:554196)\n    at fulfilled (file:///C:/Users/ARCHIN~1/AppData/Local/Temp/2H6I6CCfVwB2aamzCL6dxVRmbSB/resources/app.asar/dist/main.js:1:552860)\n    at ZoneDelegate.invoke (file:///C:/Users/ARCHIN~1/AppData/Local/Temp/2H6I6CCfVwB2aamzCL6dxVRmbSB/resources/app.asar/dist/polyfills.js:1:7275)\n    at Object.onInvoke (file:///C:/Users/ARCHIN~1/AppData/Local/Temp/2H6I6CCfVwB2aamzCL6dxVRmbSB/resources/app.asar/dist/main.js:1:202740)\n    at ZoneDelegate.invoke (file:///C:/Users/ARCHIN~1/AppData/Local/Temp/2H6I6CCfVwB2aamzCL6dxVRmbSB/resources/app.asar/dist/polyfills.js:1:7215)\n    at Zone.run (file:///C:/Users/ARCHIN~1/AppData/Local/Temp/2H6I6CCfVwB2aamzCL6dxVRmbSB/resources/app.asar/dist/polyfills.js:1:2395)\n    at file:///C:/Users/ARCHIN~1/AppData/Local/Temp/2H6I6CCfVwB2aamzCL6dxVRmbSB/resources/app.asar/dist/polyfills.js:1:14657",
   "<div class='error'>Invalid parent folder 0</div>\n",
   "Error: read ECONNRESET\nError: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)",
   "Error: read ECONNRESET\nError: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)"
  ]
 },
 "success": false,
 "created": "Mon, 29 Jan 2024 21:39:04 GMT"
}

**Comment by mvdicarlo** [comment]
Was this on the latest version of the app?
