### ISSUE TITLE
DeviantArt -- Unable to Authenticate

### ISSUE THREAD

**Issue by huang-jy** [mvdicarlo/postybirb-plus#317]
PB seems to be unable to authenticate with DA even though login is successful -- it's like it couldn't get a token or something along those lines 

![image](https://github.com/mvdicarlo/postybirb-plus/assets/2756283/94efc43e-23f5-4636-8404-1d26134c87ba)

Login is successful, as I see my "For You" section and my profile icon appears in the top-right

**Comment by leaftail1880** [comment]
This is the problem on the DA side
![stats](https://github.com/mvdicarlo/postybirb-plus/assets/110915645/e1e6cebd-9b48-4b4f-a079-6773e34218bf)

**Comment by huang-jy** [comment]
Also saw this posted to their forum: some paid users having issues uploading so yeah, probably something their side.

https://www.deviantart.com/forum/devart/general/2729801

I'll close this issue when I find out it gets fixed.
