### ISSUE TITLE
Feature request: Botright integration for captcha solving.

### ISSUE THREAD

**Issue by ghost** [mvdicarlo/postybirb-plus#325]
This could be the solution to sites that are way too overzealous with the captchas such as FA. This could enable support for posting notification posts as journals to FA which currently doesn't work as it wants you to solve a captcha each time you post a new journal.

https://github.com/Vinyzu/Botright

**Comment by mvdicarlo** [comment]
Not really easy to bundle into the app. Also generally hoping to respect websites using captchas.
I appreciate the suggestion though.
