### ISSUE TITLE
Possible feature request [?]

### ISSUE THREAD

**Issue by asterryplace** [mvdicarlo/postybirb-plus#329]
Hi! Sorry, it's legitimately my first time ever posting on github, so I apologize in advance if I mess up.

Would it be possible to set PostyBirb up so that we can use custom APIs? Or should I try my hand at making my own fork?
I'm not very experienced when it comes to coding, so I'm honestly just asking for general advice. I love this app to death, but I post to IG's Threads site pretty often, and I don't know how I could set that up; I tried fiddling with the "custom" settings, but I don't think that one's gonna work.
What should I do? And, thanks to anyone that replies!!! I'm genuinely not very software-savvy so I'm a little bit lost;;

**Comment by leaftail1880** [comment]
There is a 3 ways for adding support for the new site:
1) Implementing site inside postybirb like telegram, twitter etc, everything is written in typescript
2) Using custom website option and hosting local posting service that will take data from postybirb, transform it, handle authentification and then post to e.g. threads. This server can be written in any language.
3) Waiting for developer/contributors to add the site. However, as far as i know, insta and their apps like threads have a lot of protection from bots and automation, and authorized applications/apps costs too much, so im not sure about this option to ever happen
