### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by Lycantiger** [mvdicarlo/postybirb-plus#33]
I currently maintain the Arch Linux AUR package for https://github.com/mvdicarlo/postybirb, and I was hoping build instructions for plus could be included so I can start working on packaging this version.

**Comment by mvdicarlo** [comment]
If you go to the base directory, you can bundle everything with the "npm run build" command.

Then you'd go into electron-app and run "npm run build:linux" although you'd have to change the arch configs inside of the package.json.
