### ISSUE TITLE
Itaku: Long tags cause an Error 400 (Unknown Error) 

### ISSUE THREAD

**Issue by argonvile** [mvdicarlo/postybirb-plus#342]
When uploading an image with the tag "dr._strangelove_or:_how_i_learned_to_stop_worrying_and_love_the_bomb", itaku threw an Error 400 (Unknown Error). The log is attached below.

[1719776462405_gimmi-gimmi-gimmi-your-love-1.log](https://github.com/user-attachments/files/16045932/1719776462405_gimmi-gimmi-gimmi-your-love-1.log)

This tag is supported by other sites such as e621. When uploading the image to Itaku manually, it shortened the tag to `dr._strangelove_or:_how_i_learned_to_stop_worrying_and_love_`. Presumably PostyBirb should truncate any Itaku tags to this 60-character limit before sending them.

**Comment by mvdicarlo** [comment]
Interesting. Def will fix that this week. Not sure if it will be best to just remove the tag at that length and provide a warning or truncate manually. I don't imagine many tags are beyond 60 characters.

**Comment by mvdicarlo** [comment]
I want to say that this was fixed... having trouble recalling.

**Comment by argonvile** [comment]
I just posted the aforementioned long tag using PostyBirb, and can confirm it was correctly truncated on Itaku to `dr._strangelove_or:_how_i_learned_to_stop_worrying_and_love`. The bug has been fixed.
