### ISSUE TITLE
[DeviantArt and Newgrounds] - Fail to Post

### ISSUE THREAD

**Issue by MrEnigmaSr** [mvdicarlo/postybirb-plus#360]
```
DeviantArt: Failed to run script on page: Draft is not defined

script:

var blocksFromHTML = Draft.convertFromHTML(`
TEST MESSAGE

[Posted using PostyBirb](http://www.postybirb.com/)
`); var x = Draft.ContentState.createFromBlockArray( blocksFromHTML.contentBlocks, blocksFromHTML.entityMap, ) return JSON.stringify(Draft.convertToRaw(x))

Newgrounds: Unknown Error
9/20/2024, 1:17:23 PM
```

Number of characters and formatting of post irrelevant.  Number of tags also irrelevant.
Attempted to remove and clear account with no luck.
Errors remain.

**Comment by leaftail1880** [comment]
on 16 with the latest postybirb version posting to DA was successfull so i guess that has to do with the DA update

**Comment by leaftail1880** [comment]
This error has been confirmed and is being fixed. Ut haplened due to the update on the DA side

**Comment by MrEnigmaSr** [comment]
Deviantart seems to work fine now.  notification and art.
Newgrounds works with Art but not notification.
But to be honest, I can't even find a notification tag on my account? I dont even know if newgrounds HAS notifications?

**Comment by leaftail1880** [comment]
Anyway this is duplicate of #311

**Comment by mvdicarlo** [comment]
Closing to track in other ticket.
