### ISSUE TITLE
unable to add any accounts

### ISSUE THREAD

**Issue by leonoctem** [mvdicarlo/postybirb-plus#370]
I am trying to use postybirb for the first time, but i'm not able to add any accounts at all for some reason?

I click 'accounts' click 'add account' for FA then type in my username for FA, click 'add' and the little account alias window just closes without doing anything else. No account has been added, no further steps come up, nothing. This happens for every single site i try to add an account for.

My postybirb+ is up-to-date.
i do have a VPN but it's disconnected and the program is not running even in the background so I don't think that's interfering.
I am on windows 10

https://github.com/user-attachments/assets/2c20d905-3029-485f-a710-65b03e1c435a

Am i missing some kind of step?

**Comment by mvdicarlo** [comment]
1) Are you using OneDrive storage?
2) If you try to add a tag converter or tag group into the app does it also fail to add anything?
3) Have you used the application in the past on this computer or is this a first time?

My best guess right now is a file permissions issue within the app that might be fixable by deleting the Documents/PostyBirb directory to clear all the data and let the application re-create it by restarting it.

**Comment by leonoctem** [comment]
1. i dont use onedrive
2. i've tested adding both a tag group and tag conversion and both of those seem to work fine.
3. i had it downloaded on a computer at some point but i dont remember if it was this computer or my other one

I tried deleting the postybirb folder in documents then restarting the program, but am still unable to add any accounts

**Comment by mvdicarlo** [comment]
Sounds like I might need the logs to try and see if anything is going on under the hood. It is unusual to be able to add an account, but be fine to add other things like a tag converter or a submission file.

You can find the logs folder in %appdata%/postybirb-plus
Just zip the folder and attach it here.

**Comment by leonoctem** [comment]
after restarting my pc fully since deleting the postybirb folder, it now lets me add accounts! i think maybe it didn't re-make the folder just restarting the program and needed a complete restart to kick in.

**Comment by mvdicarlo** [comment]
Cool. Glad it is working for you now.
