### ISSUE TITLE
[BlueSky] Bluesky now requires aspectRatio field for proper image display

### ISSUE THREAD

**Issue by mistydemeo** [mvdicarlo/postybirb-plus#390]
Since a recent client release, Bluesky now requires the `aspectRatio` field to be set in order for images to be displayed correctly. Otherwise, they'll be cropped down to a square (1.95) or letterboxed into a square (later versions). It looks like the Bluesky CDN isn't calculating the aspect ratio itself from the dimensions, and requires that field to be provided at the time the image is uploaded.

Sample post:

![Screenshot 2024-12-06 at 11-50-54 CD-i (@cd-i bsky social) — Bluesky](https://github.com/user-attachments/assets/145dbe25-a62e-4082-a9ac-537557794e89)

A sample of the `aspectRatio` field can be seen here: https://docs.bsky.app/docs/tutorials/creating-a-post#images-embeds

Upstream issue: https://github.com/bluesky-social/social-app/issues/6800

**Comment by leaftail1880** [comment]
#389

**Comment by mistydemeo** [comment]
Oh, thank you! I missed that when searching.

**Comment by mistydemeo** [comment]
Fixed!
