### ISSUE TITLE
Error when posting to Itaku

### ISSUE THREAD

**Issue by Tuss36** [mvdicarlo/postybirb-plus#393]
I had a bunch of scheduled posts and they were doing just fine for a while, but starting on the 5th I've been running into an "Unknown Error" when trying to post to Itaku. I was using an older version, but updated to the current 3.1.53 in hopes of it fixing it, but no dice.

Nothing about the submissions were particularly any different from the hundreds I had posted previously, and it's affected all but one of the submissions I've tried to post since. Said one was a GIF, while the rest are static images, so it's just a bit odd that the rest won't go through.

It might be something on Itaku's API end that changed recently and hasn't gotten to being updated yet, but just figured I'd raise the issue to be looked into since it's more than just an account-login-expiry kind of thing.

**Comment by leaftail1880** [comment]
Please provide full post log from Submissions -> Logs -> View

There most likely to be more then "Unknown Error"

**Comment by Tuss36** [comment]
> Please provide full post log from Submissions -> Logs -> View
> 
> There most likely to be more then "Unknown Error"

"response": {
    "website": "Itaku",
    "time": "2024-12-13, 9:56:01 a.m.",
    "message": "Unknown Error",
    "error": 400,
    "additionalInfo": "{\n \"image\": [\n  \"Upload a valid image. The file you uploaded was either not an image or a corrupted image.\"\n ]\n}"

is I assume the relevant bit. Would certainly want that in the upload error message.

Thing is there shouldn't be anything wrong with the files themselves. They're all the same file type, none are particularly large, and even if so it's been like a half dozen in a row with different sizes/colours/etc. when the hundreds prior were fine, even though I had saved them all with the same settings.

**Comment by Tuss36** [comment]
**Update:** It seems it might be a file type thing, as given the "upload a valid image" error, I tried resaving the pictures, which didn't work, but saving them as JPEGs did work. So it seems that PNGs aren't being uploaded for some reason, which is weird because I had been able to upload several PNGs prior to this error happening.

So that narrows it down at least. At least it's not an impassable situation, but still quite inconvenient, especially when it was working before.

**Comment by mvdicarlo** [comment]
Was your image large enough to need resizing within the app? It could possibly be related to that.

**Comment by Tuss36** [comment]
**Update 2**: I believe it may have something to do with some kind of meta data GIMP puts in, as pngs exported from another program work, but not ones from GIMP. I haven't updated my GIMP installation in yonks though, so I don't know what would be different between uploads, nor which setting would be the problem as I always just leave them as the default. But then at that point it's more an Itaku problem than a Postybirb problem, so I suppose I'll take it up with them instead and you can close this issue. Though if someone else can also reach out to them to bring it to their awareness it'd be appreciated.
