### ISSUE TITLE
Weasyl: Checking the "Notify" setting disables Notifications

### ISSUE THREAD

**Issue by tux93** [mvdicarlo/postybirb-plus#42]
After noticing missing Notifications for Submissions of some Artists on Weasyl I got in touch with one of them and they told me they're using PostyBirb+

With some test submissions of my own I found that the "Notify" setting in PostyBirb+ seems to do the exact opposite of what it implies: checking it disables notifying followers, unchecking enables it.

I think two things should change:  
- change the default to off  
- change the label so that it is clear checking it will disable Submission Notifications

**Comment by mvdicarlo** [comment]
Will look into it this week.
Could have accidentally switched the behavior.

**Comment by mvdicarlo** [comment]
@tux93 Should be fixed in the latest version of 3.0.30 once people update to it.
https://github.com/mvdicarlo/postybirb-plus/commit/5364ea580158306face4f2352724fef7053c3908
