### ISSUE TITLE
Fedora Linux -- Snap displays squares

### ISSUE THREAD

**Issue by huang-jy** [mvdicarlo/postybirb-plus#68]
![image](https://user-images.githubusercontent.com/2756283/148076402-e8df1c96-5229-4600-a703-7a595c32aaca.png)

I suspect this maybe related to a missing font somewhere

**Comment by mvdicarlo** [comment]
Appears to just be a snap issue. Not really sure I can do anything about it for you since I don't manage the packaging tool.

https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/86

**Comment by huang-jy** [comment]
That's also a ticket I was looking at. Trying a few things. I'm not sure it's snap since I used the same snap under Ubuntu, so likely to be something Ubuntu is doing that Fedora isn't.

**Comment by huang-jy** [comment]
Nope, nothing worked so far. I'll just use the AppImage for now.
