### ISSUE TITLE
DeviantArt -- Status updates do not preserve newlines

### ISSUE THREAD

**Issue by huang-jy** [mvdicarlo/postybirb-plus#70]
When posting from PB+ and posting a "status update" on DeviantArt, any newlines seem to be stripped. Posting the same thing at the same time to other places seems fine.

The status update format does support newlines as I can go back and modify the update that PB made, and add the missing newlines to it.

**Comment by leaftail1880** [comment]
Still actual? I found [that](https://github.com/mvdicarlo/postybirb-plus/blob/e44b6f46cb9cc1e504b2a6a1bc31c19138870536/electron-app/src/server/websites/deviant-art/deviant-art.service.ts#L174)
```js
.replace(/\n/g, '')
```

**Comment by mvdicarlo** [comment]
Could be worth seeing if that fixes it.
If that is all that is wrong.

**Comment by leaftail1880** [comment]
@huang-jy @mvdicarlo that was it. When posting deviation all newlines was replaced by <br>, but when posting notification not. Also tag limit in deviantart is 30, not 200, so ill open pr to fix that

**Comment by leaftail1880** [comment]
can be closed now

**Comment by leaftail1880** [comment]
> can be closed now

@mvdicarlo

**Comment by leaftail1880** [comment]
> can be closed now

@huang-jy

**Comment by huang-jy** [comment]
Just to confirm, this will be fixed in the next released version?

**Comment by leaftail1880** [comment]
> Just to confirm, this will be fixed in the next released version?

yup, all things from develop are going to release

**Comment by huang-jy** [comment]
Perfect, I will close the issue then. Thanks for all the hard work resolving this 😄

**Comment by mvdicarlo** [comment]
I plan to do a new release between now and Monday.
