### ISSUE TITLE
Postybirb Mastodon does not work with Pleroma and possibly other non-Mastodon ActivityPub instances

### ISSUE THREAD

**Issue by Pawlicker** [mvdicarlo/postybirb-plus#88]
When I try to post anything with Postybirb 3.0.46 to a [Pleroma](https://pleroma.social) instance using Postybirb's Mastodon interface, posts don't show up. A friend on the other hand had issues logging into his [Soapbox-FE](https://soapbox.pub/) Pleroma instance and I'm not sure if it works with Misskey or not. As there are a lot of non-Mastodon fediverse instances out there, I feel it should either be supported or noted that it is in fact Mastodon only.

**Comment by mvdicarlo** [comment]
I don't really have a definitive answer for you. Briefly looking at their api docs they mention they are based on mastodon with changes. So depending on what those changes are it might break things.

If you have trouble posting the failure log dropped in the logs tab might give a better hint.

**Comment by leaftail1880** [comment]
@qazmlp still actual? Since this issue is opened, mastodon lib changed to megaladon, wich may support pleroma

**Comment by qazmlp** [comment]
I'll have to check, but this could take a few days¹.

¹ sent from the Eurofurence registration queue. I'm probably too busy this week.

**Comment by bugsysop** [comment]
Managed to connect to Pleroma with Mastodon account template.

Working:
- Login to one or more accounts
- Posting a 'File' or a 'Notification
- Publication of image
- Schedule a publication
- Crossposting (tested with Tumblr)

Not working:
- Markdown in posts (no conversion from editor rich text)
- 'Alt' for images not transfered

Have a nice day

**Comment by qazmlp** [comment]
(Sorry that I didn't manage to do this. Things have been busy here and I would have had to find an instance and make an account first to test.)

**Comment by bugsysop** [comment]
@qazmlp If you need an account I can provide one on a Pleroma test instance

**Comment by aneillans** [comment]
Pleroma support added in PR #262
