### ISSUE TITLE
Derpibooru/Furbooru: Switch to Markdown

### ISSUE THREAD

**Issue by Meow** [mvdicarlo/postybirb-plus#97]
I'm copying [this issue](https://github.com/mvdicarlo/postybirb/issues/100) here as well, as this seems to be relevant to both projects.

Original issue text:

> Derpibooru and Furbooru have deprecated and removed the old Textile syntax, and have switched to Markdown. This causes all posts created by PostyBirb with any kind of text formatting for description to appear broken. The formatter for both sites would need to be updated.
> 
> Both use the exact same version of CommonMark-GFM with some additions and alterations. [You may use this guide as reference](https://derpibooru.org/pages/markdown).

**Comment by mvdicarlo** [comment]
Done.
